services:
    #Time twig extension
    cocorico_time.twig.time_extension:
        class: Cocorico\TimeBundle\Twig\TimeExtension
        arguments:
          - "%cocorico.time_unit%"
          - "%cocorico.time_unit_allday%"
        tags:
            - { name: twig.extension }
