version: "3.7"
   
services:
  mariadb:
    container_name: bitoubi_mysql
    image: mariadb:10.5
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=cocorico
        - MYSQL_PASSWORD=cocorico
        - MYSQL_USER=cocorico
        - MYSQL_DATABASE=cocorico
    ports:
      - "9306:3306"
    networks:
      - cocorico 
    volumes:
      - mariadb_data:/var/lib/mysql

  bitoubi:
    container_name: bitoubi_symfony
    build:
        context: .
        target: dev-auto
        dockerfile: ./docker/Dockerfile
        args:
          - SQL_HOST=bitoubi_mysql
          - SQL_PORT=3306
          - SQL_USER=cocorico
          - SQL_PASS=cocorico
          - GGL_KEY1=
          - GGL_KEY2=
          - SMTP_HOST=
          - SMTP_PORT=25
          - SMTP_USER=
          - SMTP_PASSWORD=
    volumes:
      - ./src:/cocorico/src
      - ./web:/cocorico/web
      - ./app/Resources:/cocorico/app/Resources
    environment:
     - ITOU_ENV=local_dev
    networks:
      - cocorico 
    ports:
      - "9090:80"
    depends_on:
      - mariadb

volumes:
    mariadb_data:

networks:
    cocorico:
        driver: bridge
