services:
    sonata.admin.footer:
        class: Cocorico\CMSBundle\Admin\FooterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site", label: "Footers", label_catalogue: "cocorico_admin_menu" }
        arguments:
            - ~
            - Cocorico\CMSBundle\Entity\Footer
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]
            - [ setFooterManager, ["@cocorico_cms.footer.manager"]]
