# docker run --name cocorico -ti -p 9090:9090 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -e HOST_UID=$UID cocolabs/cocorico
#
from debian:buster-slim

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/home/cocorico \
    HOME=/home/cocorico \
    HOST_UID=1000 \
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

ARG HOST_PORT=9090
ARG GGL_KEY1=none
ARG GGL_KEY2=none


ENV SQL_HOST=localhost \
    SQL_PORT=3306 \
    SQL_NAME=cocorico \
    SQL_USER=cocorico \
    SQL_PASS=cocorico \
    HOST_PORT=$HOST_PORT \
    GGL_KEY1=$GGL_KEY1 \
    GGL_KEY2=$GGL_KEY2 \
    APP_ENV=dev \
    SYMFONY_ENV=dev 


RUN apt-get update

RUN apt-get install -y \
        curl \
        git \
        default-mysql-client \ 
        imagemagick \ 
        unzip \
        wget \
        gnupg \
        systemd \
        mariadb-server \
        default-mysql-client

ENTRYPOINT ["bash"]
RUN apt-get install -y \
        php7.3 \
        php7.3-fpm \
        php7.3-curl \
        php7.3-zip \
        php7.3-mbstring \
        php7.3-xml \
        php7.3-intl \
        php7.3-gd \
        php-dom \
        php-imagick \
        php-mysql


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer global require hirak/prestissimo 
RUN  groupadd cocorico && useradd -g cocorico --create-home cocorico

# COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.default.conf /etc/nginx/sites-enabled/default

COPY . /cocorico
WORKDIR cocorico

COPY ./docker/parameters.yml /cocorico/app/config/parameters.yml
RUN sed -i -e 's|%SQL_HOST%|'"$SQL_HOST"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_PORT%|'"$SQL_PORT"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_NAME%|'"$SQL_NAME"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_USER%|'"$SQL_USER"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_PASS%|'"$SQL_PASS"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%HOST_PORT%|'"$HOST_PORT"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%GGL_KEY1%|'"$GGL_KEY1"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%GGL_KEY2%|'"$GGL_KEY2"'|' /cocorico/app/config/parameters.yml \
    && cat /cocorico/app/config/parameters.yml

COPY ./docker/docker_full_init.sh ./init_services
RUN ls
VOLUME /data/db

ENTRYPOINT ["bash"]
# RUN composer install

# # Init database and other stuff
# RUN /docker/docker_full_init.sql
# 
# RUN clevercloud/post_build_hook.sh
# RUN wget https://get.symfony.com/cli/installer -O - | bash
# 
# # RUN useradd -ms /bin/bash _www && chown -R _www:_www ./var
# # RUN service nginx restart && service php7.3-fpm start
# COPY ./docker/run.sh ./run
# COPY ./docker/run_css.sh ./run_css
# RUN echo "Start Symfony server with:\n\
# /home/cocorico/.symfony/bin/symfony server:start --no-tls --port 80\n\
# "
# CMD ["bash"]
# CMD ["/home/cocorico/.symfony/bin/symfony", "server:start", "--no-tls", "--port 80"]
