# docker run --name cocorico -ti -p 9090:9090 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -e HOST_UID=$UID cocolabs/cocorico
#
from debian:buster-slim

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/home/cocorico \
    HOME=/home/cocorico \
    HOST_UID=1000 \
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

ARG HOST_PORT=9090
ARG GGL_KEY1=none
ARG GGL_KEY2=none
ARG ITOU_HOST=none


ENV SQL_HOST=localhost \
    SQL_PORT=3306 \
    SQL_NAME=cocorico \
    SQL_USER=cocorico \
    SQL_PASS=cocorico \
    HOST_PORT=$HOST_PORT \
    GGL_KEY1=$GGL_KEY1 \
    GGL_KEY2=$GGL_KEY2 \
    ITOU_HOST=$ITOU_HOST \
    APP_ENV=dev \
    SYMFONY_ENV=dev 


RUN apt-get update

RUN apt-get install -y \
        curl \
        git \
        default-mysql-client \ 
        imagemagick \ 
        unzip \
        wget \
        gnupg \
        systemd \
        mariadb-server \
        vim-tiny \
        default-mysql-client

# Add Yarn & PHP
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update

RUN apt-get install -y \
        yarn \
        php7.3 \
        php7.3-fpm \
        php7.3-curl \
        php7.3-zip \
        php7.3-mbstring \
        php7.3-xml \
        php7.3-intl \
        php7.3-gd \
        php-dom \
        php-imagick \
        php-mysql


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN composer global require hirak/prestissimo 
RUN  groupadd cocorico && useradd -g cocorico --create-home cocorico

# COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.default.conf /etc/nginx/sites-enabled/default

COPY . /cocorico
WORKDIR cocorico

COPY ./docker/parameters.yml /cocorico/app/config/parameters.yml
RUN sed -i -e 's|%SQL_HOST%|'"$SQL_HOST"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_PORT%|'"$SQL_PORT"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_NAME%|'"$SQL_NAME"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_USER%|'"$SQL_USER"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SQL_PASS%|'"$SQL_PASS"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%HOST_PORT%|'"$HOST_PORT"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%GGL_KEY1%|'"$GGL_KEY1"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%GGL_KEY2%|'"$GGL_KEY2"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%ITOU_HOST%|'"$ITOU_HOST"'|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SMTP_HOST%|localhost|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SMTP_USER%|user|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SMTP_PASSWORD%|password|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%SMTP_PORT%|587|' /cocorico/app/config/parameters.yml \
    && sed -i -e 's|%ITOU_ENV%|local_dev|' /cocorico/app/config/parameters.yml \
    && cat /cocorico/app/config/parameters.yml

COPY ./docker/docker_full_init.sh ./init_services
VOLUME /data/db
#
# Init database and other stuff
RUN ./init_services

RUN composer install && yarn install
RUN clevercloud/post_build_hook.sh
RUN wget https://get.symfony.com/cli/installer -O - | bash
COPY ./docker/run_all.sh ./run

# CMD ["./run"]
ENTRYPOINT ["bash"]
