# MessageBundle
fos_message:
    db_driver:              orm
    thread_class:           Cocorico\MessageBundle\Entity\Thread
    message_class:          Cocorico\MessageBundle\Entity\Message
    composer:               cocorico_message.composer
    new_thread_form:
        factory:            fos_message.new_thread_form.factory.default # See FormFactory\NewThreadMessageFormFactory
        type:               Cocorico\MessageBundle\Form\Type\Frontend\NewThreadMessageFormType    # See FormType\NewThreadMessageFormType
        handler:            cocorico_message.new_thread.form.handler # See FormHandler\NewThreadMessageFormHandler
        model:              Cocorico\MessageBundle\FormModel\NewThreadMessage
        name:               message
    reply_form:
        factory:            fos_message.reply_form.factory.default      # See FormFactory\ReplyMessageFormFactory
        type:               FOS\MessageBundle\FormType\ReplyMessageFormType         # See FormType\ReplyMessageFormType
        handler:            fos_message.reply_form.handler.default      # See FormHandler\ReplyMessageFormHandler
        name:               message