services:
    sonata.admin.review:
        class: Cocorico\ReviewBundle\Admin\ReviewAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Reviews" }
        arguments:
            - ~
            - Cocorico\ReviewBundle\Entity\Review
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
