 #Disable Sonata Admin User Group
services:
    sonata.user.admin.group:
        abstract: true
        public: false

    sonata.admin.user_address:
        class: Cocorico\UserBundle\Admin\UserAddressAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Cocorico\UserBundle\Entity\UserAddress
            - ~
        calls:
            - [ setTranslationDomain, [cocorico_user]]
            - [ setLocales, ["%cocorico.locales%"]]