services:
    cocorico_user.authentication_subscriber:
        class: Cocorico\UserBundle\Event\UserAuthenticationSubscriber
        arguments:
            - "@session"
            - "%cocorico.time_zone%"
        tags:
            - { name: kernel.event_subscriber }

    cocorico_user.subscriber:
        class: Cocorico\UserBundle\Event\UserSubscriber
        tags:
            - { name: kernel.event_subscriber}