cocorico_geo:
    google_place_api_key: "%cocorico_geo.google_place_api_key%"
    google_place_server_api_key: "%cocorico_geo.google_place_server_api_key%"
    ipinfodb_api_key: "%cocorico_geo.ipinfodb_api_key%"