parameters:
    database_host: '%MYSQL_ADDON_HOST%'
    database_port: '%MYSQL_ADDON_PORT%'
    database_name: '%MYSQL_ADDON_DB%'
    database_user: '%MYSQL_ADDON_USER%'
    database_password: '%MYSQL_ADDON_PASSWORD%'
    mongodb_server: '%MONGODB_ADDON_URI%'
    mongodb_database_name: '%MONGODB_ADDON_DB%'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    mailer_port: null
    secret: d69958a4fff6ba8f0f4fc4fc2657366ccf9dd0f3
    use_assetic_controller: false
    cocorico.assets_base_urls: '%BASE_URL%'
    router.request_context.host: localhost
    router.request_context.scheme: http
    router.request_context.base_url: ''
    cocorico.admin: admin
    cocorico.admin_translation: false
    cocorico.check_translation: false
    cocorico.translator.secret.key: null
    cocorico.facebook.app_id: none
    cocorico.facebook.secret: none
    cocorico.image_driver: imagick
    cocorico.google_analytics: UA-64445856-1
    cocorico.google_tag_manager: false
    cocorico_geo.google_place_api_key: null
    cocorico_geo.google_place_server_api_key: null
    cocorico_geo.ipinfodb_api_key: null
    cocorico.deploy.host: fake.cocorico.prod
    cocorico.deploy.dir: /fake/path
    cocorico.deploy.user: fakeuser
    cocorico.booking.expiration_delay: 2880
    cocorico.booking.acceptation_delay: 240
    cocorico.booking.alert_expiration_delay: 120
    cocorico.booking.alert_imminent_delay: 1440
    cocorico.booking.validated_moment: start
    cocorico.booking.validated_delay: 0
    cocorico.bankwire_checking_simulation: false
