services:
    sonata.admin.parameter:
        class: Cocorico\ConfigBundle\Admin\ParameterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: true, group: "Site", label: "Configuration" }
        arguments:
            - ~
            - Cocorico\ConfigBundle\Entity\Parameter
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]