name: PHP Staging Deploy

on:
  push:
    branches-ignore: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # See https://github.com/marketplace/actions/deploy-to-clever-cloud
    - uses: actions/checkout@v2
    - name: Local shallow copy
      run: git fetch --prune --unshallow
    # Deploy to clever cloud
    - name: Deploy to Staging
      uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.APP_STAGING }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
